name: quansuanlingshou
on:
  workflow_dispatch:
  schedule:
    - cron: '29 5/6 * * *'
jobs:  # 5492
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quansuanlingshou
        env:
          i05: ${{ secrets.i05 }}
        run: |
          echo $i05 | jq -r .qjfds43 | /bin/bash
          echo $bij83 | jq -r .t59 | /bin/bash

